### PR TITLE
Adding more endpoints and geometry capabilities

### PR DESCRIPTION
**Pull request by greglucas**
# New API capabilities

Changing the workflow for the frontend interactions. Added several new endpoints and a user_id that is used to store files.

* New `/api/geometry` and `/api/geometry/sat_name` endpoints.
* The old `/api/image` endpoint now requires a user_id to get the proper image back, so the call now looks like `/api/image/<uniqueId that geometry endpoint returned>`
* Calls the Matlab function with the proper geometry file for the user.

## Standard workflow

No geometry file so just submit to `/api/singlepoint`

## New workflow with geometry

1. Upload geometry file `/api/geometry`. Save the returned `userId`
2. Submit the data and run to `/api/singlepoint/userId`, which will run the case and return the data payload.
3. GET the output image if desired from `/api/image/userId`. NOTE: It is dependent on calling `/api/singlepoint/userId` first to produce the proper image.

## Questions

Is the /tmp directory OK to write to? How long will items stay there, will it overflow? We could write a cronjob to clean up the directory on a schedule or something if need be too. Or if we want to store things we can write out to an EFS or s3 bucket.

### CODE REVIEW

**Comment by kimyx** [comment]
"userId" doesn't seem like a good name for the returned identifier. Perhaps "geometry_id"?

Should there be some way to check for pre-existing geometries? If they can be identified as identical (especially for sat_name), why store them again? Perhaps store a name and checksum alongside the image data in each geometry directory. Leads to the need for an indexing system, though.

**Comment by kimyx** [comment]
I wouldn't save anything desired for long-term storage in the /tmp directory. It's convenient and fast, but likely to go away, especially if we have to rebuild the EB instance. By default, there is no automatic cleanup in /tmp, but there's a built-in mechanism for doing so in linux:

https://www.thegeekdiary.com/centos-rhel-67-why-the-files-in-tmp-directory-gets-deleted-periodically/

We use this for MMS SDC.

Anyway, I'd recommend storing such geometry data in EFS or S3 so that we don't need to take special steps when transitioning to a new EB instance, which is almost certain to happen again.

**Comment by greglucas** [comment]
> Should there be some way to check for pre-existing geometries? If they can be identified as identical (especially for sat_name), why store them again?

The pre-existing geometries are stored in the local `vector-code` repo which I then copy over (could make a symlink instead I suppose). The image and triangle file have to be remade each time because those are dependent on the orientation of the object which is sent in from the frontend, so those are unique to each userId.

None of this is long-term storage, so it sounds like you think this is an OK approach for now? I view those directories as temporary "sessions" for each user, hence the `userId` name. I can change to `geometryId` instead.

**Comment by kimyx** [comment]
Fair enough. If they aren't needed long-term, /tmp is fine. We should document the "lifetime" of them so users know. The auto-cleanup can be as fast as daily. We'll need to build the setup into the EB deploy if cleanup is desired.

**Review by kimyx — APPROVED** [review]
Code looks good to me.

**Comment by greglucas** [comment]
OK, I merged it in, Kim.

It might be worthwhile to implement that cleanup script in a follow-up PR just to make sure that we don't have files sitting there for long periods of time.

Additionally, we will need to update the submodule once the new vector-code updates are merged in.

**Pull request merged**
